- name: Install Node Exporter on Ubuntu & RedHat-based OS
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.9.0"
    node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    install_path: "/usr/local/bin"
    service_name: "node_exporter"
    user_name: "node_exporter"
    group_name: "node_exporter"

  tasks:
    - name: Detect OS Family
      ansible.builtin.debug:
        msg: "Running on {{ ansible_os_family }} ({{ ansible_distribution }})"

    - name: Install required dependencies (Ubuntu)
      ansible.builtin.apt:
        name: 
          - wget
          - tar
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required dependencies (RedHat)
      ansible.builtin.yum:
        name: 
          - wget
          - tar
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create node_exporter user
      ansible.builtin.user:
        name: "{{ user_name }}"
        shell: /sbin/nologin
        system: yes
        create_home: no

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: "{{ node_exporter_url }}"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "{{ install_path }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: '0755'

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: "/etc/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User={{ user_name }}
          Group={{ group_name }}
          Type=simple
          ExecStart={{ install_path }}/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd and enable Node Exporter
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Open firewall port 9100 (Ubuntu - UFW)
      community.general.ufw:
        rule: allow
        port: "9100"
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Open firewall port 9100 (RedHat - Firewalld)
      ansible.builtin.shell: |
        firewall-cmd --add-port=9100/tcp --permanent
        firewall-cmd --reload
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Verify Node Exporter is running
      ansible.builtin.command: "systemctl status node_exporter"
      register: service_status
      changed_when: false

    - name: Show Node Exporter status
      ansible.builtin.debug:
        msg: "{{ service_status.stdout }}"
