---
- name: Install Prometheus on Ubuntu
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    prometheus_version: "2.53.3"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_install_dir: "/usr/local/bin"
    prometheus_config_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"
    prometheus_service_file: "/etc/systemd/system/prometheus.service"
  
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - wget
          - tar
          - curl
        state: present

    - name: Create Prometheus user
      user:
        name: "{{ prometheus_user }}"
        shell: "/sbin/nologin"
        create_home: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus archive
      ansible.builtin.unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /tmp/prometheus-{{ prometheus_version }}-linux-amd64/prometheus /tmp/prometheus-{{ prometheus_version }}-linux-amd64/promtool {{ prometheus_install_dir }}
    
    - name: Set permissions for Prometheus binaries
      file:
        path: "{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_install_dir }}/prometheus"
        - "{{ prometheus_install_dir }}/promtool"

    - name: Move Prometheus config files
      command: mv /tmp/prometheus-{{ prometheus_version }}-linux-amd64/consoles /tmp/prometheus-{{ prometheus_version }}-linux-amd64/console_libraries {{ prometheus_config_dir }}

    - name: Copy Prometheus configuration file
      template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'

    - name: Create Prometheus systemd service file
      template:
        src: prometheus.service.j2
        dest: "{{ prometheus_service_file }}"
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
