---
- name: Install Node Exporter v1.9.0
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:

    - name: Download Node Exporter v1.9.0
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        mode: '0644'

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create Node Exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /usr/sbin/nologin
        system: yes

    - name: Set ownership for Node Exporter
      ansible.builtin.file:
        path: "/usr/local/bin/node_exporter"
        owner: node_exporter
        group: node_exporter
        mode: '0755'

    - name: Create Node Exporter systemd service
      ansible.builtin.copy:
        dest: "/etc/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Node Exporter v1.9.0
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Allow firewall rule for Node Exporter (9100/tcp)
      ansible.builtin.firewalld:
        port: 9100/tcp
        permanent: yes
        state: enabled
      ignore_errors: yes

    - name: Restart firewall
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
      ignore_errors: yes
