---
- name: Deploy Prometheus
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - software-properties-common

    - name: Add Prometheus APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: yes

    - name: Import GPG key for Prometheus
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
